name: open-risk-register
region: ams

static_sites:
  - name: web
    github:
      repo: Oak3-Advisory/open-risk-register
      branch: main
      deploy_on_push: true
    index_document: index.html
    catchall_document: index.html
